### PR TITLE
Initial services buildout

### PR DESCRIPTION
**Pull request by xannor**
## Description

This is my initial buildout of a services approach. It provides the following services.

clear_block -- this will clear the blocked state, and reset the block timer
set_stay_on -- this will set the stay flag to true to force stay on on the next activate
set_stay_off -- this will set the stay flag false to allow the controller to turn the light off after the next activate
set_night_mode -- this will change the start and end times for night mode. Added an additional now and constraint value support so the mode can be started/ended right now or when the day constraint time, also having both start and end unset sets them to midnight which should disable night mode.

## Related Issues

In response to #125 but may have impact on other issues.

Also a possible idea to start #136 as I attempted to start moving content into a file structure I have seen many home assistant projects use.

Closes

Nothing so far as there may be more to implement.

### CODE REVIEW

**Comment by xannor** [comment]
Im going to try to get a readme update done this weekend, had little time this week for it.

**Comment by xannor** [comment]
I got some basic docs in, I'm not a tech writer so hopefully this is good enough. I tried to fit it into the structure you have.

**Comment by mikeage** [comment]
This is a very nice feature! Can I nitpick a bit about the name, though? I understand that the variable is called `stay` and it means "Keep the light on once triggered and never turn off", and so the service is called `set_stay_on`, which is parsed as "set stay_mode to on". However, not being familiar with the new `stay` feature, I first though that these two services would "set the light to stay on, always" and "set the light to stay off, always" (i.e., `set_stay_off` meant "set 'stay off' mode", i.e., disable the motion detection (what I call "nap mode", so you can sleep without having the lights turn on every time you toss in bed ;-) ). 

Perhaps something like `enable_stay` and `disable_stay`? (or even `enable_stay_on`; rebrand the `stay` option as `stay_on`?). Using enable/disable instead of on/off avoids the confusion of whether we're turning on stay or whether we're setting "stay on".

Thanks!

**Comment by mikeage** [comment]
(and I know that the `stay` option isn't from this PR, and the comment is really more of a general note about the new feature)

**Comment by mikeage** [comment]
fair enough. I know it's late. Just thinking that better late than never, and maybe it's not *too* late

**Pull request merged**
